
icons:
  - changed-files:
    - any-glob-to-any-file: svgs/*
    - any-glob-to-any-file: app/assets/appfilter.xml

code:
  - all:
    - changed-files: # Not indented as it either had the same or better results
        - any-glob-to-any-file: 'app/**'
        - any-glob-to-all-files: '!app/src/main/res/*/strings.xml'
        - any-glob-to-all-files: '!app/assets/appfilter.xml'